### ISSUE TITLE
有其他端的插件吗

### ISSUE THREAD

**Issue by jiangyin14** [Mooling0602/Matrix-MCDR#2]
服务器并未运行MCDReforged
是否有CraftBukkit或Spigot版本？

**Comment by Mooling0602** [comment]
关于 Spigot 版本，你可以尝试 MatrixSpigotBridge；
同时建议你尝试一下 MCDReforged，这和现有的 BukkitAPI 插件不会产生任何冲突

**Comment by jiangyin14** [comment]
好的谢谢
