### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by IMSaltlyFish** [Mooling0602/Matrix-MCDR#3]
1、变量名混乱，使用驼峰命名法可以改善代码可读性而不是使用_来作为单词的分隔
2、所有函数均写在__init__.py中，没有明确的访问权限设置
3、不建议使用.json文件作为配置文件，建议使用.yml作为配置文件的格式

**Comment by Mooling0602** [comment]
1.
变量名称已尝试进行改善，部分变量名来自于三方项目文档，个人认为不适合再行修改，以免产生问题；
  2.
感谢你的建议，经过初步优化后的新版本（v2.0.0）将很快发布；
  3.
关于配置文件格式，其他的插件都在使用json格式，且MCDR的文档中和配置文件加载相关的部分也都采用了此格式，因此暂时没有计划进行更改。

________________________________
发件人: IMSaltlyFish ***@***.***>
发送时间: 2024年5月20日 16:46
收件人: Mooling0602/MatrixSync-MCDR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Mooling0602/MatrixSync-MCDR] Issues (Issue #3)


1、变量名混乱，使用驼峰命名法可以改善代码可读性而不是使用_来作为单词的分隔
2、所有函数均写在__init__.py中，没有明确的访问权限设置
3、不建议使用.json文件作为配置文件，建议使用.yml作为配置文件的格式

―
